# Generated by Django 4.2.5 on 2023-09-20 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0014_survey_redirect_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='created_by_user',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='user id'),
        ),
        migrations.AddField(
            model_name='survey',
            name='tenant_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='tenant_id'),
        ),
    ]
