# Generated by Django 4.2.5 on 2023-09-22 01:37

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0016_remove_survey_is_published_survey_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='publish_date',
        ),
        migrations.AddField(
            model_name='survey',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Create date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='survey',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Update date'),
        ),
    ]
