# Generated by Django 4.2.5 on 2023-10-04 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0017_remove_survey_publish_date_survey_create_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='subscribe_uuid',
            field=models.CharField(blank=True, max_length=36, null=True, verbose_name='Subscriber unique identifier'),
        ),
    ]
