# Generated by Django 4.2.5 on 2023-10-04 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0018_response_subscribe_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='response',
            old_name='subscribe_uuid',
            new_name='subscriber_uuid',
        ),
    ]
